services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile_servidor
    container_name: servidor1
    ports:
      - 50051:50051

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_cliente
    container_name: cliente1
    depends_on:
      - servidor